# Generated by Django 4.2 on 2025-07-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topalltimewinner',
            name='winner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='competition.winner'),
        ),
    ]
