# Generated by Django 4.2 on 2025-07-20 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('apis', '0001_initial'),
        ('giftshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topalltimewinner',
            name='winner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apis.winner'),
        ),
        migrations.AddField(
            model_name='livedraw',
            name='competitions',
            field=models.ManyToManyField(to='apis.competition'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.competition'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.userprofile'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='giftshop.order'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='giftshop.sale'),
        ),
        migrations.AddField(
            model_name='competitioneditlog',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.competition'),
        ),
        migrations.AddField(
            model_name='competitioneditlog',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.userprofile'),
        ),
        migrations.AddField(
            model_name='competitioncopyhistory',
            name='copied_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.userprofile'),
        ),
        migrations.AddField(
            model_name='competitioncopyhistory',
            name='new_competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copied_versions', to='apis.competition'),
        ),
        migrations.AddField(
            model_name='competitioncopyhistory',
            name='original_competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_sources', to='apis.competition'),
        ),
        migrations.AddField(
            model_name='clientactionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.userprofile'),
        ),
    ]
