# Generated by Django 4.2 on 2025-07-26 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_cart_order_productcategory_product_orderitem_and_more'),
        ('adminpanel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='apis.order'),
        ),
    ]
