# Generated by Django 4.2 on 2025-06-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
