# Generated by Django 4.2 on 2025-07-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='ticketinstantwin',
            name='instant_win_prize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.instantwinprize'),
        ),
        migrations.AddField(
            model_name='ticketinstantwin',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='competition.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competition'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ecard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition.ecard'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='instantwinprize',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competition'),
        ),
        migrations.AddField(
            model_name='discountcoupon',
            name='competition_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition.competitiongroup'),
        ),
        migrations.AddField(
            model_name='competitionprize',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='competition.competition'),
        ),
        migrations.AddField(
            model_name='competition',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition.competitiongroup'),
        ),
        migrations.AddField(
            model_name='competition',
            name='prize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.prize'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketlock',
            unique_together={('competition', 'letter', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('competition', 'ticket_number')},
        ),
    ]
