# Generated by Django 4.2 on 2025-07-20 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis', '0001_initial'),
        ('giftshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatetransaction',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giftshop.order'),
        ),
        migrations.AddField(
            model_name='affiliatetransaction',
            name='withdrawal_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.affiliatewithdrawal'),
        ),
        migrations.AddField(
            model_name='affiliateprofile',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate', to='apis.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('competition', 'ticket_number')},
        ),
    ]
