# Generated by Django 4.2 on 2025-07-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='ticket_quantity',
        ),
        migrations.AddField(
            model_name='competition',
            name='tickets_per_letter',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
