# Generated by Django 4.2 on 2025-07-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_remove_competition_ticket_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='ticket_number_limit',
        ),
    ]
